services:
  backend:
    build: ./backend
    container_name: cloudshop-backend
    restart: unless-stopped
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: cloudshop-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

